#!/bin/bash

PYTHON_VERSION="2.7.3"
VIRTUALENV_VERSION="1.9.1"
PCRE_VERSION="8.35"
NGINX_VERSION="1.4.0"
MEMCACHED_VERSION="1.4.20"

PYTHON_CURRENT=`${OPENSHIFT_DATA_DIR}/bin/python -c 'import sys; print(".".join(map(str, sys.version_info[:3])))'`
if [ "$PYTHON_CURRENT" != "$PYTHON_VERSION" ]; then
	echo "*** Install Python-${PYTHON_VERSION}"
	cd $OPENSHIFT_TMP_DIR
	wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.bz2
	tar -jxf Python-${PYTHON_VERSION}.tar.bz2
	cd Python-${PYTHON_VERSION}
	./configure --prefix=$OPENSHIFT_DATA_DIR
	make install
fi

#if [ ! -d $OPENSHIFT_DATA_DIR/virtualenv ]; then
	#echo "*** Install virtualenv-${VIRTUALENV_VERSION}"
	#cd $OPENSHIFT_TMP_DIR
	#wget https://pypi.python.org/packages/source/v/virtualenv/virtualenv-${VIRTUALENV_VERSION}.tar.gz
	#tar -zxf virtualenv-${VIRTUALENV_VERSION}.tar.gz
	#cd virtualenv-${VIRTUALENV_VERSION}
	#$OPENSHIFT_DATA_DIR/bin/python virtualenv.py $OPENSHIFT_DATA_DIR/virtualenv
#fi

#if [ ! -d $OPENSHIFT_DATA_DIR/nginx/sbin ]; then
	#echo "*** Install nginx-'${NGINX_VERSION}'"
    #cd $OPENSHIFT_TMP_DIR
    #wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-${PCRE_VERSION}.tar.bz2
    #wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
    #tar -jxf pcre-${PCRE_VERSION}.tar.bz2
    #tar -zxf nginx-${NGINX_VERSION}.tar.gz
    #cd nginx-${NGINX_VERSION}
    #mkdir $OPENSHIFT_DATA_DIR/nginx
    #./configure --prefix=$OPENSHIFT_DATA_DIR/nginx --with-pcre=$OPENSHIFT_TMP_DIR/pcre-${PCRE_VERSION} --with-http_realip_module
    #make && make install && make clean
#fi

#if [ ! -f $OPENSHIFT_DATA_DIR/bin/memcached ]; then
	#echo "*** Install memcached-'${MEMCACHED_VERSION}'"
    #cd $OPENSHIFT_TMP_DIR
	#wget http://www.memcached.org/files/memcached-${MEMCACHED_VERSION}.tar.gz
    #tar -zxf memcached-${MEMCACHED_VERSION}.tar.gz
    #cd memcached-${MEMCACHED_VERSION}
    #./configure --prefix=$OPENSHIFT_DATA_DIR
    #make && make install
#fi

# cleanup
rm -rf $OPENSHIFT_TMP_DIR/*
